version: '3.6'

services:

  php:
    image: php:7.2-symfony-fpm
    volumes:
    - ".:/opt/project"
  nginx:
    image: nginx
    volumes:
      - "./docker/check24.test.conf:/etc/nginx/conf.d/check24.test.conf"
    ports:
      - 80:80