services:
  admin.entry:
    class: AppBundle\Admin\EntryAdmin
    arguments: [~, AppBundle\Entity\Entry, ~]
    tags:
    - { name: sonata.admin, manager_type: orm, label: Entry }
  admin.banned:
    class: AppBundle\Admin\BannedIpAdmin
    arguments: [~, AppBundle\Entity\BannedIp, ~]
    tags:
    - { name: sonata.admin, manager_type: orm, label: BannedIp }
  handler.entry:
    class: AppBundle\Handler\EntryHandler
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@mailer"